networks:
  app-network:
    driver: bridge
services:
  app:
    container_name: laravel-blog-prod
    image: laravel-blog:prod
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: laravel
        uid: 1000
    restart: unless-stopped
    tty: true
    ports:
      - 9000:9000
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
  db:
    container_name: laravel-blog-db-test
    image: postgres:16.6
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - app-network
  webserver:
    image: nginx:1.27.3
    container_name: nginx-webserver-test
    restart: unless-stopped
    tty: true
    ports:
      - 3005:80
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./infra/nginx/conf:/etc/nginx/conf.d
    networks:
      - app-network
volumes:
  db-data:
    driver: local
