networks:
  app-network:
    driver: bridge
services:
  db:
    container_name: laravel-blog-db
    image: postgres:16.6
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - app-network
  webserver:
    image: nginx:1.27.3
    container_name: laravel-blog-webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./infra/nginx/conf/:/etc/nginx/conf.d
      - shared-storage:/var/www
    ports:
      - 8000:80
    depends_on:
      - app
      - db
    networks:
      - app-network
  app:
    build:
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      - APP_ENV=production
    container_name: laravel-blog
    image: mochfajrin/laravel-blog:latest
    restart: unless-stopped
    volumes:
      - shared-storage:/var/www
    tty: true
    ports:
      - 9000:9000
    networks:
      - app-network
    depends_on:
      - db
volumes:
  shared-storage:
  db-data:
    driver: local
